name: tasktrack
description: A task management application with SQLite integration for CRUD operations.
publish_to: "none" # This is a private project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0
  path_provider: ^2.0.15




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
